### ISSUE TITLE
How to run on Localhost?

### ISSUE THREAD

**Issue by TheMashaBrand** [usewayfinder/Wayfinder#2]
Hi, how do you run this framework on Localhost, it seems not to be working. Thanks.

**Comment by cchana** [comment]
Hi, have you pointed your host file to the `/www/` folder? The `index.php` file is the one that calls the framework which then does all the hard work. Hopefully that gets you going!

I have it set up with MAMP locally and tested on Ubuntu, so not sure how well it works on other operating systems.

**Comment by TheMashaBrand** [comment]
The Wayfinder is located in my http://localhost/projects/Framework/Wayfinder/, if I go to the folder /www/ it says 
  - Notice: Undefined property: Wayfinder::$url in C:\xampp\htdocs\projects\Framework\Wayfinder\framework\Wayfinder.php on line 355
And gives 404 not Found

**Comment by cchana** [comment]
Ah ok. So Wayfinder uses the URL to route your request. It has to be the root of your project. http://localhost has to map to the `www` folder for it to work.

**Comment by TheMashaBrand** [comment]
Can it be possible to put a $base_url="" somewhere in the code, to let Wayfinder know where to start in the case of the URL.

Some other frameworks like Laravel, Codeigniter, Slim has this.

**Comment by cchana** [comment]
I'll have a think about it. My initial reaction was to say no but maybe it is a useful thing to offer. I'll update you if it happens!

**Comment by TheMashaBrand** [comment]
Thank you so much.
